# Generated by Django 3.2.4 on 2022-07-24 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='photo',
            field=models.ImageField(default='image', upload_to='about'),
            preserve_default=False,
        ),
    ]
