# Generated by Django 3.2.4 on 2022-07-24 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_about_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='address',
            field=models.CharField(default='ok', max_length=255),
            preserve_default=False,
        ),
    ]
