# Generated by Django 3.2.4 on 2021-06-12 02:59

import blog.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', blog.models.UserManager()),
            ],
        ),
    ]
