# Generated by Django 3.2.4 on 2021-06-13 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20210613_0537'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_on',
            field=models.DateField(auto_now=True),
        ),
    ]
